#pragma once

// clang-format off
#include <glad/glad.h>
#include <GLFW/glfw3.h>
// clang-format on
// must be first OpenGL header

#include <glm/glm.hpp>
#include <imgui.h>

#include "Camera/Camera.hpp"
#include "Camera/OrthographicCamera.hpp"
#include "Camera/OrthographicCameraController.hpp"
#include "Camera/PerspectiveCamera.hpp"
#include "Camera/PerspectiveCameraController.hpp"
#include "Codes/GamepadCodes.hpp"
#include "Codes/KeyCodes.hpp"
#include "Codes/MouseCodes.hpp"
#include "Core.hpp"
#include "Events/ApplicationEvent.hpp"
#include "Events/Event.hpp"
#include "Events/EventQueue.hpp"
#include "Events/GamepadEvent.hpp"
#include "Events/KeyEvent.hpp"
#include "Events/MouseEvent.hpp"
#include "ImGui/ImGuiLayer.hpp"
#include "Input/Input.hpp"
#include "Layers/Layer.hpp"
#include "Layers/LayerStack.hpp"
#include "Logs/Log.hpp"
#include "MaterialSystem/OpenGL/OpenGLTexture2D.hpp"
#include "MaterialSystem/Texture.hpp"
#include "Math/Transform.hpp"
#include "Renderer/BufferLayout.hpp"
#include "Renderer/FrameBuffer.hpp"
#include "Renderer/GraphicsContext.hpp"
#include "Renderer/IndexBuffer.hpp"
#include "Renderer/OpenGL/OpenGLContext.hpp"
#include "Renderer/OpenGL/OpenGLFrameBuffer.hpp"
#include "Renderer/OpenGL/OpenGLIndexBuffer.hpp"
#include "Renderer/OpenGL/OpenGLRendererAPI.hpp"
#include "Renderer/OpenGL/OpenGLShader.hpp"
#include "Renderer/OpenGL/OpenGLVertexArray.hpp"
#include "Renderer/OpenGL/OpenGLVertexBuffer.hpp"
#include "Renderer/Renderer.hpp"
#include "Renderer/Shader.hpp"
#include "Renderer/VertexArray.hpp"
#include "Renderer/VertexBuffer.hpp"
#include "Time/Time.hpp"
#include "Time/Timestep.hpp"
#include "Window.hpp"
#include "spdlog/async.h"
#include "spdlog/async_logger.h"
#include "spdlog/common.h"
#include "spdlog/logger.h"
#include "spdlog/sinks/basic_file_sink.h"
#include "spdlog/sinks/rotating_file_sink.h"
#include "spdlog/sinks/stdout_color_sinks.h"
#include "spdlog/spdlog.h"
#include <algorithm>
#include <atomic>
#include <chrono>
#include <cstdint>
#include <exception>
#include <format>
#include <iomanip>
#include <iostream>
#include <memory>
#include <mutex>
#include <ranges>
#include <ratio>
#include <string>
#include <unordered_map>
