#pragma once

#define GLM_ENABLE_EXPERIMENTAL
// clang-format off
#include <glad/glad.h>
#include <GLFW/glfw3.h>
// clang-format on
// must be first OpenGL header

#include <glm/glm.hpp>
#include <imgui.h>

#include <BuiltInShaders/Light.hpp>
#include <BuiltInShaders/LightManager.hpp>
#include <BuiltInShaders/ShaderLibrary.hpp>
#include <BuiltInShaders/ShaderSources.hpp>
#include <Camera/Camera.hpp>
#include <Camera/OrthographicCamera.hpp>
#include <Camera/OrthographicCameraController.hpp>
#include <Camera/PerspectiveCamera.hpp>
#include <Camera/PerspectiveCameraController.hpp>
#include <Codes/GamepadCodes.hpp>
#include <Codes/KeyCodes.hpp>
#include <Codes/MouseCodes.hpp>
#include <Core.hpp>
#include <Events/ApplicationEvent.hpp>
#include <Events/Event.hpp>
#include <Events/EventQueue.hpp>
#include <Events/GamepadEvent.hpp>
#include <Events/KeyEvent.hpp>
#include <Events/MouseEvent.hpp>
#include <ImGui/ImGuiLayer.hpp>
#include <Input/Input.hpp>
#include <Layers/Layer.hpp>
#include <Layers/LayerStack.hpp>
#include <Logs/Log.hpp>
#include <MaterialSystem/Material.hpp>
#include <MaterialSystem/MaterialLibrary.hpp>
#include <MaterialSystem/OpenGL/OpenGLTexture2D.hpp>
#include <MaterialSystem/PBRMaterial.hpp>
#include <MaterialSystem/PhongMaterial.hpp>
#include <MaterialSystem/Texture.hpp>
#include <MaterialSystem/UnlitMaterial.hpp>
#include <Math/Transform.hpp>
#include <MeshSystem/Mesh.hpp>
#include <MeshSystem/MeshFactory.hpp>
#include <MeshSystem/Vertex.hpp>
#include <ModelLoader/GLTFLoader.hpp>
#include <ModelLoader/Model.hpp>
#include <ModelLoader/ModelRenderer.hpp>
#include <Renderer/BufferLayout.hpp>
#include <Renderer/FrameBuffer.hpp>
#include <Renderer/GraphicsContext.hpp>
#include <Renderer/IndexBuffer.hpp>
#include <Renderer/OpenGL/OpenGLContext.hpp>
#include <Renderer/OpenGL/OpenGLFrameBuffer.hpp>
#include <Renderer/OpenGL/OpenGLIndexBuffer.hpp>
#include <Renderer/OpenGL/OpenGLRendererAPI.hpp>
#include <Renderer/OpenGL/OpenGLShader.hpp>
#include <Renderer/OpenGL/OpenGLVertexArray.hpp>
#include <Renderer/OpenGL/OpenGLVertexBuffer.hpp>
#include <Renderer/Renderer.hpp>
#include <Renderer/Shader.hpp>
#include <Renderer/VertexArray.hpp>
#include <Renderer/VertexBuffer.hpp>
#include <Scene/ECS/Component.hpp>
#include <Scene/ECS/Entity.hpp>
#include <Scene/Scene.hpp>
#include <Scene/SceneManager.hpp>
#include <Scene/SceneRenderer.hpp>
#include <Scene/SceneSerializer.hpp>
#include <Scripting/API/BE_SCRIPT_API.h>
#include <Scripting/API/ScriptAPIInternal.hpp>
#include <Scripting/Core/HotReloadManager.hpp>
#include <Scripting/Core/ScriptComponent.hpp>
#include <Scripting/Core/ScriptEngineManager.hpp>
#include <Scripting/Core/ScriptField.hpp>
#include <Scripting/Core/ScriptInstance.hpp>
#include <Scripting/Core/ScriptRegistry.hpp>
#include <Scripting/Core/ScriptTypes.hpp>
#include <Scripting/Lua/LuaBindings.hpp>
#include <Scripting/Lua/LuaClassSystem.hpp>
#include <Scripting/Lua/LuaCoroutine.hpp>
#include <Scripting/Lua/LuaDebugger.hpp>
#include <Scripting/Lua/LuaEngine.hpp>
#include <Scripting/Lua/LuaInstance.hpp>
#include <Scripting/Lua/LuaSandbox.hpp>
#include <Scripting/Lua/LuaTypeDefinitions.hpp>
#include <Time/Time.hpp>
#include <Time/Timestep.hpp>
#include <Window.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <glm/gtx/matrix_decompose.hpp>
#include <spdlog/async.h>
#include <spdlog/async_logger.h>
#include <spdlog/common.h>
#include <spdlog/logger.h>
#include <spdlog/sinks/basic_file_sink.h>
#include <spdlog/sinks/rotating_file_sink.h>
#include <spdlog/sinks/stdout_color_sinks.h>
#include <spdlog/spdlog.h>
#include <tiny_gltf.h>
